apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-05-22T12:40:16Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "437"
  uid: 51a8a933-cd37-4b69-a6c1-c3e0e7dfbaa6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.133.114
  clusterIPs:
  - 10.104.133.114
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32649
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
